package com.orangedietc.flim.po;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.review_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.floor
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.reply_to
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer replyTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.thumb_up
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer thumbUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.time_stamp
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Date timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_id
     *
     * @return the value of comments.comment_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_id
     *
     * @param commentId the value for comments.comment_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.review_id
     *
     * @return the value of comments.review_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.review_id
     *
     * @param reviewId the value for comments.review_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.floor
     *
     * @return the value of comments.floor
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.floor
     *
     * @param floor the value for comments.floor
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.reply_to
     *
     * @return the value of comments.reply_to
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getReplyTo() {
        return replyTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.reply_to
     *
     * @param replyTo the value for comments.reply_to
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setReplyTo(Integer replyTo) {
        this.replyTo = replyTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.userid
     *
     * @return the value of comments.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.userid
     *
     * @param userid the value for comments.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.thumb_up
     *
     * @return the value of comments.thumb_up
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getThumbUp() {
        return thumbUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.thumb_up
     *
     * @param thumbUp the value for comments.thumb_up
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setThumbUp(Integer thumbUp) {
        this.thumbUp = thumbUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.time_stamp
     *
     * @return the value of comments.time_stamp
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.time_stamp
     *
     * @param timeStamp the value for comments.time_stamp
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}