package com.orangedietc.flim.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MoviesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public MoviesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMovieIdIsNull() {
            addCriterion("movie_id is null");
            return (Criteria) this;
        }

        public Criteria andMovieIdIsNotNull() {
            addCriterion("movie_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovieIdEqualTo(Integer value) {
            addCriterion("movie_id =", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotEqualTo(Integer value) {
            addCriterion("movie_id <>", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThan(Integer value) {
            addCriterion("movie_id >", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_id >=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThan(Integer value) {
            addCriterion("movie_id <", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThanOrEqualTo(Integer value) {
            addCriterion("movie_id <=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdIn(List<Integer> values) {
            addCriterion("movie_id in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotIn(List<Integer> values) {
            addCriterion("movie_id not in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdBetween(Integer value1, Integer value2) {
            addCriterion("movie_id between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_id not between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andImdbIdIsNull() {
            addCriterion("imdb_id is null");
            return (Criteria) this;
        }

        public Criteria andImdbIdIsNotNull() {
            addCriterion("imdb_id is not null");
            return (Criteria) this;
        }

        public Criteria andImdbIdEqualTo(String value) {
            addCriterion("imdb_id =", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdNotEqualTo(String value) {
            addCriterion("imdb_id <>", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdGreaterThan(String value) {
            addCriterion("imdb_id >", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdGreaterThanOrEqualTo(String value) {
            addCriterion("imdb_id >=", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdLessThan(String value) {
            addCriterion("imdb_id <", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdLessThanOrEqualTo(String value) {
            addCriterion("imdb_id <=", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdLike(String value) {
            addCriterion("imdb_id like", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdNotLike(String value) {
            addCriterion("imdb_id not like", value, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdIn(List<String> values) {
            addCriterion("imdb_id in", values, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdNotIn(List<String> values) {
            addCriterion("imdb_id not in", values, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdBetween(String value1, String value2) {
            addCriterion("imdb_id between", value1, value2, "imdbId");
            return (Criteria) this;
        }

        public Criteria andImdbIdNotBetween(String value1, String value2) {
            addCriterion("imdb_id not between", value1, value2, "imdbId");
            return (Criteria) this;
        }

        public Criteria andMovieTitleIsNull() {
            addCriterion("movie_title is null");
            return (Criteria) this;
        }

        public Criteria andMovieTitleIsNotNull() {
            addCriterion("movie_title is not null");
            return (Criteria) this;
        }

        public Criteria andMovieTitleEqualTo(String value) {
            addCriterion("movie_title =", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleNotEqualTo(String value) {
            addCriterion("movie_title <>", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleGreaterThan(String value) {
            addCriterion("movie_title >", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleGreaterThanOrEqualTo(String value) {
            addCriterion("movie_title >=", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleLessThan(String value) {
            addCriterion("movie_title <", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleLessThanOrEqualTo(String value) {
            addCriterion("movie_title <=", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleLike(String value) {
            addCriterion("movie_title like", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleNotLike(String value) {
            addCriterion("movie_title not like", value, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleIn(List<String> values) {
            addCriterion("movie_title in", values, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleNotIn(List<String> values) {
            addCriterion("movie_title not in", values, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleBetween(String value1, String value2) {
            addCriterion("movie_title between", value1, value2, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andMovieTitleNotBetween(String value1, String value2) {
            addCriterion("movie_title not between", value1, value2, "movieTitle");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(Float value) {
            addCriterion("rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(Float value) {
            addCriterion("rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(Float value) {
            addCriterion("rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(Float value) {
            addCriterion("rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(Float value) {
            addCriterion("rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(Float value) {
            addCriterion("rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<Float> values) {
            addCriterion("rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<Float> values) {
            addCriterion("rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(Float value1, Float value2) {
            addCriterion("rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(Float value1, Float value2) {
            addCriterion("rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andMovieProfileIsNull() {
            addCriterion("movie_profile is null");
            return (Criteria) this;
        }

        public Criteria andMovieProfileIsNotNull() {
            addCriterion("movie_profile is not null");
            return (Criteria) this;
        }

        public Criteria andMovieProfileEqualTo(String value) {
            addCriterion("movie_profile =", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileNotEqualTo(String value) {
            addCriterion("movie_profile <>", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileGreaterThan(String value) {
            addCriterion("movie_profile >", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileGreaterThanOrEqualTo(String value) {
            addCriterion("movie_profile >=", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileLessThan(String value) {
            addCriterion("movie_profile <", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileLessThanOrEqualTo(String value) {
            addCriterion("movie_profile <=", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileLike(String value) {
            addCriterion("movie_profile like", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileNotLike(String value) {
            addCriterion("movie_profile not like", value, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileIn(List<String> values) {
            addCriterion("movie_profile in", values, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileNotIn(List<String> values) {
            addCriterion("movie_profile not in", values, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileBetween(String value1, String value2) {
            addCriterion("movie_profile between", value1, value2, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andMovieProfileNotBetween(String value1, String value2) {
            addCriterion("movie_profile not between", value1, value2, "movieProfile");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNull() {
            addCriterion("release_date is null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIsNotNull() {
            addCriterion("release_date is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseDateEqualTo(Date value) {
            addCriterionForJDBCDate("release_date =", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("release_date <>", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThan(Date value) {
            addCriterionForJDBCDate("release_date >", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_date >=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThan(Date value) {
            addCriterionForJDBCDate("release_date <", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_date <=", value, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateIn(List<Date> values) {
            addCriterionForJDBCDate("release_date in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("release_date not in", values, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_date between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andReleaseDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_date not between", value1, value2, "releaseDate");
            return (Criteria) this;
        }

        public Criteria andGenresIsNull() {
            addCriterion("genres is null");
            return (Criteria) this;
        }

        public Criteria andGenresIsNotNull() {
            addCriterion("genres is not null");
            return (Criteria) this;
        }

        public Criteria andGenresEqualTo(String value) {
            addCriterion("genres =", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresNotEqualTo(String value) {
            addCriterion("genres <>", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresGreaterThan(String value) {
            addCriterion("genres >", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresGreaterThanOrEqualTo(String value) {
            addCriterion("genres >=", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresLessThan(String value) {
            addCriterion("genres <", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresLessThanOrEqualTo(String value) {
            addCriterion("genres <=", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresLike(String value) {
            addCriterion("genres like", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresNotLike(String value) {
            addCriterion("genres not like", value, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresIn(List<String> values) {
            addCriterion("genres in", values, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresNotIn(List<String> values) {
            addCriterion("genres not in", values, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresBetween(String value1, String value2) {
            addCriterion("genres between", value1, value2, "genres");
            return (Criteria) this;
        }

        public Criteria andGenresNotBetween(String value1, String value2) {
            addCriterion("genres not between", value1, value2, "genres");
            return (Criteria) this;
        }

        public Criteria andPosterIsNull() {
            addCriterion("poster is null");
            return (Criteria) this;
        }

        public Criteria andPosterIsNotNull() {
            addCriterion("poster is not null");
            return (Criteria) this;
        }

        public Criteria andPosterEqualTo(String value) {
            addCriterion("poster =", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotEqualTo(String value) {
            addCriterion("poster <>", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterGreaterThan(String value) {
            addCriterion("poster >", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterGreaterThanOrEqualTo(String value) {
            addCriterion("poster >=", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLessThan(String value) {
            addCriterion("poster <", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLessThanOrEqualTo(String value) {
            addCriterion("poster <=", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterLike(String value) {
            addCriterion("poster like", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotLike(String value) {
            addCriterion("poster not like", value, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterIn(List<String> values) {
            addCriterion("poster in", values, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotIn(List<String> values) {
            addCriterion("poster not in", values, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterBetween(String value1, String value2) {
            addCriterion("poster between", value1, value2, "poster");
            return (Criteria) this;
        }

        public Criteria andPosterNotBetween(String value1, String value2) {
            addCriterion("poster not between", value1, value2, "poster");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 19 18:43:51 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}