package com.orangedietc.flim.po;

import java.util.Date;

import javax.validation.constraints.NotNull;

public class Movies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.movie_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.imdb_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    @NotNull(message="{movies.imdbId.isNULL}")
    private String imdbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.movie_title
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    @NotNull(message="{movies.title.isNULL}")
    private String movieTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.rating
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Float rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.movie_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String movieProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.release_date
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.genres
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String genres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.poster
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String poster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.summary
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.movie_id
     *
     * @return the value of movies.movie_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.movie_id
     *
     * @param movieId the value for movies.movie_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.imdb_id
     *
     * @return the value of movies.imdb_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getImdbId() {
        return imdbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.imdb_id
     *
     * @param imdbId the value for movies.imdb_id
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setImdbId(String imdbId) {
        this.imdbId = imdbId == null ? null : imdbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.movie_title
     *
     * @return the value of movies.movie_title
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getMovieTitle() {
        return movieTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.movie_title
     *
     * @param movieTitle the value for movies.movie_title
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle == null ? null : movieTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.rating
     *
     * @return the value of movies.rating
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Float getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.rating
     *
     * @param rating the value for movies.rating
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setRating(Float rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.movie_profile
     *
     * @return the value of movies.movie_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getMovieProfile() {
        return movieProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.movie_profile
     *
     * @param movieProfile the value for movies.movie_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setMovieProfile(String movieProfile) {
        this.movieProfile = movieProfile == null ? null : movieProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.release_date
     *
     * @return the value of movies.release_date
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.release_date
     *
     * @param releaseDate the value for movies.release_date
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.genres
     *
     * @return the value of movies.genres
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getGenres() {
        return genres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.genres
     *
     * @param genres the value for movies.genres
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setGenres(String genres) {
        this.genres = genres == null ? null : genres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.poster
     *
     * @return the value of movies.poster
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.poster
     *
     * @param poster the value for movies.poster
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setPoster(String poster) {
        this.poster = poster == null ? null : poster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.summary
     *
     * @return the value of movies.summary
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.summary
     *
     * @param summary the value for movies.summary
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }
}