package com.orangedietc.flim.po;

import java.util.Date;

import javax.validation.constraints.Email;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Past;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userid
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    @NotBlank(message="username must not be empty")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.hashed_pwd
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private String hashedPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.salt
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    @Email(message="invalid email address")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.location
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    @Min(0)
    @Max(2)
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birthday
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    @Past(message="birthday must be in the past")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.intro
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userid
     *
     * @return the value of users.userid
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userid
     *
     * @param userid the value for users.userid
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.hashed_pwd
     *
     * @return the value of users.hashed_pwd
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getHashedPwd() {
        return hashedPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.hashed_pwd
     *
     * @param hashedPwd the value for users.hashed_pwd
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setHashedPwd(String hashedPwd) {
        this.hashedPwd = hashedPwd == null ? null : hashedPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.salt
     *
     * @return the value of users.salt
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.salt
     *
     * @param salt the value for users.salt
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.location
     *
     * @return the value of users.location
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.location
     *
     * @param location the value for users.location
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birthday
     *
     * @return the value of users.birthday
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birthday
     *
     * @param birthday the value for users.birthday
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.intro
     *
     * @return the value of users.intro
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.intro
     *
     * @param intro the value for users.intro
     *
     * @mbg.generated Sat May 05 18:47:14 EDT 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}