package com.orangedietc.flim.po;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.hashed_pwd
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String hashedPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.salt
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.location
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    private String userProfile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userid
     *
     * @return the value of users.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userid
     *
     * @param userid the value for users.userid
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.hashed_pwd
     *
     * @return the value of users.hashed_pwd
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getHashedPwd() {
        return hashedPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.hashed_pwd
     *
     * @param hashedPwd the value for users.hashed_pwd
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setHashedPwd(String hashedPwd) {
        this.hashedPwd = hashedPwd == null ? null : hashedPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.salt
     *
     * @return the value of users.salt
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.salt
     *
     * @param salt the value for users.salt
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.location
     *
     * @return the value of users.location
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.location
     *
     * @param location the value for users.location
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_profile
     *
     * @return the value of users.user_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public String getUserProfile() {
        return userProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_profile
     *
     * @param userProfile the value for users.user_profile
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile == null ? null : userProfile.trim();
    }
}