package com.orangedietc.flim.mapper;

import com.orangedietc.flim.po.Movies;
import com.orangedietc.flim.po.MoviesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoviesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    long countByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int deleteByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int deleteByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int insert(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int insertSelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    List<Movies> selectByExampleWithBLOBs(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    List<Movies> selectByExample(MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    Movies selectByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByExampleSelective(@Param("record") Movies record, @Param("example") MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Movies record, @Param("example") MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByExample(@Param("record") Movies record, @Param("example") MoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByPrimaryKeySelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByPrimaryKeyWithBLOBs(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbg.generated Thu Apr 19 18:43:51 EDT 2018
     */
    int updateByPrimaryKey(Movies record);
}